### ISSUE TITLE
We have 2 'Identity.User' Tables

### ISSUE THREAD

**Issue by 274188A** [erossini/NET8BlazorIdentity#2]
Nice code!

Noticed we have 2 User Tables - however only `AspNetUsers` seems to be utilised.

Assume we can drop the other from the schema?

![Screenshot 2023-11-09 111020](https://github.com/erossini/NET8BlazorIdentity/assets/40014477/ce556e08-2ee3-4f11-85d8-cfed372683b8)

![image](https://github.com/erossini/NET8BlazorIdentity/assets/40014477/f6652a80-0030-49b2-a786-a111f260cfa4)

#3 created

**Comment by erossini** [comment]
Thank you for your PR.
Enrico
